version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: /home/ec2-user/stop.sh
      timeout: 60
      runas: linux
  ApplicationStart:
    - location: /home/ec2-user/start.sh
      timeout: 60
      runas: linux